# Generated by Django 5.2.5 on 2025-08-31 02:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productimage_productvariant_alter_brand_slug_and_more"),
        ("orders", "0003_fill_cartitem_unit_price"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="uniq_cart_product_variant",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("cart", "product"),
                name="uniq_cart_product_no_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("cart", "product", "variant"),
                name="uniq_cart_product_with_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="cartitem_quantity_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="orderitem_quantity_gt_0"
            ),
        ),
    ]
