# Generated by Django 5.2.5 on 2025-09-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_cartitem_uniq_cart_product_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
