# Generated by Django 5.2.5 on 2025-09-04 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_address_options_alter_user_options_and_more"),
        ("catalog", "0003_productvariant_is_active"),
        ("customers", "0003_remove_address_customer_alter_customer_options_and_more"),
        ("orders", "0005_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_orders",
                to="accounts.address",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="orders_cart_cart_id_dc9f49_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["number"], name="orders_orde_number_539d36_idx"),
        ),
    ]
