# Generated by Django 5.2.5 on 2025-09-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_shipping_address_alter_orderitem_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
