# Generated by Django 5.2.5 on 2025-09-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_orderitem_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("base_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("est_days_min", models.PositiveSmallIntegerField(default=2)),
                ("est_days_max", models.PositiveSmallIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("card", "Credit/Debit Card"),
                    ("gateway", "Online Gateway"),
                    ("fake", "Fake (Demo)"),
                ],
                default="gateway",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="IRR", max_length=3)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("card", "Credit/Debit Card"),
                            ("gateway", "Online Gateway"),
                            ("fake", "Fake (Demo)"),
                        ],
                        default="gateway",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="initiated",
                        max_length=12,
                    ),
                ),
                ("gateway_ref", models.CharField(blank=True, max_length=100)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("raw_request", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.shippingmethod",
            ),
        ),
    ]
