# Generated by Django 5.2.5 on 2025-09-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_shippingmethod_alter_order_payment_method_payment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
    ]
