# Generated by Django 5.2.5 on 2025-09-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_payment_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
