# Generated by Django 5.2.5 on 2025-09-08 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_address_options_alter_user_options_and_more"),
        ("orders", "0010_delete_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="accounts.address",
            ),
        ),
    ]
