# Generated by Django 5.2.5 on 2025-09-09 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_shipping_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.shippingmethod",
            ),
        ),
    ]
