# Generated by Django 5.2.5 on 2025-09-10 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="orders.shippingmethod",
            ),
        ),
    ]
