# Generated by Django 5.2.5 on 2025-10-05 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_address"),
        ("orders", "0014_alter_order_status_orderstatuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_orders",
                to="customers.address",
            ),
        ),
    ]
