# Generated by Django 5.2.5 on 2025-08-29 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-is_default", "id"]},
        ),
        migrations.AddField(
            model_name="address",
            name="province",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                default="GB", help_text="ISO 3166-1 alpha-2 (e.g. GB, US, IR)", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="address",
            name="line1",
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name="address",
            name="line2",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?[0-9\\s\\-()]{6,20}$",
                            )
                        ],
                    ),
                ),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="customers.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["customer", "is_default"], name="customers_a_custome_d08d94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["postal_code"], name="customers_a_postal__89520f_idx"),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("customer",),
                name="uniq_default_address_per_customer",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["created_at"], name="customers_c_created_1ed0f4_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="customers_c_phone_8493fa_idx"),
        ),
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
    ]
