# Generated by Django 5.2.5 on 2025-09-04 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_customerprofile_user_alter_address_options_and_more"),
    ]

    operations = [
        # --- تغییرات مرتبط با Customer ---
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="customers_c_created_1ed0f4_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="customers_c_phone_8493fa_idx",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="marketing_opt_in",
            new_name="newsletter_opt_in",
        ),
        migrations.AddField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^[0-9+\-()\s]{6,}$", message="Enter a valid phone number."
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
