# Generated by Django 5.2.5 on 2025-10-05 01:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_remove_address_customer_alter_customer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-()\\s]{6,}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                ("line1", models.CharField(max_length=255, verbose_name="Address line 1")),
                (
                    "line2",
                    models.CharField(blank=True, max_length=255, verbose_name="Address line 2"),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "province",
                    models.CharField(blank=True, max_length=100, verbose_name="State/Province"),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="IR", max_length=2)),
                ("default_shipping", models.BooleanField(default=False)),
                ("default_billing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-default_shipping", "-default_billing", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("default_shipping", True)),
                        fields=("user",),
                        name="uniq_default_shipping_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("default_billing", True)),
                        fields=("user",),
                        name="uniq_default_billing_per_user",
                    ),
                ],
            },
        ),
    ]
