# Generated by Django 5.2.5 on 2025-10-05 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-default_shipping", "-default_billing", "-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="address",
            name="uniq_default_shipping_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="address",
            name="uniq_default_billing_per_user",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="default_billing",
            new_name="default_billing",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="default_shipping",
            new_name="default_shipping",
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default_shipping", True)),
                fields=("user",),
                name="uniq_default_shipping_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default_billing", True)),
                fields=("user",),
                name="uniq_default_billing_per_user",
            ),
        ),
    ]
