# Generated by Django 5.2.5 on 2025-09-04 01:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_verified_user_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ("-is_default", "-created_at")},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("shipping", "Shipping"), ("billing", "Billing")],
                default="shipping",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="Iran", max_length=80),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9+\\-()\\s]{6,}$", message="Enter a valid phone number."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user", "address_type"),
                name="unique_default_address_per_type_per_user",
            ),
        ),
    ]
