# Generated by Django 5.2.5 on 2025-10-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_address_options_alter_user_options_and_more"),
        ("orders", "0015_alter_order_shipping_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
