repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        files: \.py$
        exclude: ^(node_modules/|migrations/|\.venv/)
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --recursive

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: \.py$
        exclude: ^(node_modules/|migrations/|\.venv/)

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: \.py$
        exclude: ^(node_modules/|migrations/|\.venv/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        files: \.py$
        exclude: ^(node_modules/|migrations/|\.venv/)
        args: [--fix]
