# Generated by Django 5.2.5 on 2025-10-11 01:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0016_alter_orderitem_unit_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invoice_number", models.CharField(max_length=20, unique=True)),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=20)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number", "issue_date"],
                        name="invoices_in_invoice_c00063_idx",
                    )
                ],
            },
        ),
    ]
