# Generated by Django 5.2.5 on 2025-10-12 01:56

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-issued_at"]},
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_in_invoice_c00063_idx",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_number",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="issue_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid"), ("canceled", "Canceled")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
