# Generated by Django 5.2.5 on 2025-10-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issued_at"],
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
    ]
