# Generated by Django 5.2.5 on 2025-09-07 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_payment_order"),
        ("payments", "0002_alter_payment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["created_at"], name="payments_pa_created_b8a300_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["method"], name="payments_pa_method__c21427_idx"),
        ),
    ]
