# Generated by Django 5.2.5 on 2025-09-10 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_cart_shipping_method"),
        ("payments", "0003_alter_payment_amount_alter_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_status_7ad4af_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_created_b8a300_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_method__c21427_idx",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="raw_gateway_payload",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="IRR", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(default="fake", max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
