# Generated by Django 5.2.5 on 2025-09-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_cart_shipping_method"),
        ("payments", "0004_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Amount in smallest currency unit (e.g., IRR)."
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="External payment/tracking id provided by the gateway.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(db_index=True, default="fake", max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "provider"], name="payments_pa_status_eb2eec_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["created_at"], name="payments_pa_created_b8a300_idx"),
        ),
    ]
