# Generated by Django 5.2.5 on 2025-09-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productimage_productvariant_alter_brand_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
