# Generated by Django 5.2.5 on 2025-09-09 02:18
from decimal import Decimal
from django.db import migrations


def coerce_prices(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductVariant = apps.get_model("catalog", "ProductVariant")

    for p in Product.objects.all():
        try:
            p.price = Decimal(str(p.price))
            p.save(update_fields=["price"])
        except Exception:
            pass

    for v in ProductVariant.objects.all():
        try:
            v.extra_price = Decimal(str(v.extra_price))
            v.save(update_fields=["extra_price"])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_price_alter_productvariant_extra_price"),
    ]

    operations = [
        migrations.RunPython(coerce_prices, migrations.RunPython.noop),
    ]
