# Generated by Django 5.2.5 on 2025-09-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_coerce_prices_to_decimal"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "brand"], name="catalog_pro_is_acti_1b0d83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "category"], name="catalog_pro_is_acti_1a8de5_idx"
            ),
        ),
    ]
