# Generated by Django 5.2.5 on 2025-09-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_catalog_pro_is_acti_1b0d83_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="uniq_primary_image_per_product",
            ),
        ),
    ]
