# Generated by Django 5.2.5 on 2025-09-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productimage_uniq_primary_image_per_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="extra_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
