# Generated by Django 5.2.5 on 2025-10-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Mark this product as featured to display it on the homepage or highlighted sections.",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured"], name="catalog_pro_is_acti_e6e001_idx"
            ),
        ),
    ]
